package com.maityp394.studentapi.exception;

import jakarta.servlet.http.HttpServletRequest;
import java.net.URI;
import java.time.Instant;
import java.util.LinkedHashMap;
import java.util.Map;
import lombok.extern.slf4j.Slf4j;
import org.jspecify.annotations.NonNull;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.http.*;
import org.springframework.web.bind.MethodArgumentNotValidException;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.RestControllerAdvice;
import org.springframework.web.context.request.ServletWebRequest;
import org.springframework.web.context.request.WebRequest;
import org.springframework.web.method.annotation.HandlerMethodValidationException;
import org.springframework.web.method.annotation.MethodArgumentTypeMismatchException;
import org.springframework.web.servlet.mvc.method.annotation.ResponseEntityExceptionHandler;

/**
 * Centralized global exception interceptor providing RFC 9457 Problem Details for HTTP APIs.
 *
 * <p>Translates application business exceptions, Spring validation errors, type mismatches, and
 * database constraint conflicts into standardized {@link ProblemDetail} responses. This class
 * extends Spring's {@link ResponseEntityExceptionHandler} to integrate with standard Spring MVC
 * exception handling mechanisms while overriding key methods to conform to the RFC 9457
 * specification.
 *
 * <h3>RFC 9457 Response Structure</h3>
 *
 * <p>Standard fields include:
 *
 * <ul>
 *   <li>{@code type} - A URI reference identifying the problem type (defaults to {@code
 *       "about:blank"})
 *   <li>{@code title} - A short, human-readable summary of the problem type
 *   <li>{@code status} - The HTTP status code generated by the origin server
 *   <li>{@code detail} - A human-readable explanation specific to this occurrence
 *   <li>{@code instance} - A URI reference identifying the specific occurrence of the problem
 * </ul>
 *
 * <h3>Custom Extension Properties</h3>
 *
 * <ul>
 *   <li>{@code code} - Machine-readable {@link ErrorCode} identifier (e.g., {@code
 *       "STUDENT_NOT_FOUND"})
 *   <li>{@code timestamp} - UTC {@link Instant} representing the timestamp when the error was
 *       captured
 *   <li>{@code errors} - Key-value map of field validation failures, present only on validation
 *       errors
 * </ul>
 *
 * <h3>Example RFC 9457 Error Response</h3>
 *
 * <pre>{@code
 * {
 *   "type": "about:blank",
 *   "title": "Resource Not Found",
 *   "status": 404,
 *   "detail": "Student not found: a1b2c3d4-...",
 *   "instance": "/api/v1/students/a1b2c3d4-...",
 *   "code": "STUDENT_NOT_FOUND",
 *   "timestamp": "2026-09-04T11:00:00Z"
 * }
 * }</pre>
 *
 * <h3>Example Validation Error Response</h3>
 *
 * <pre>{@code
 * {
 *   "type": "about:blank",
 *   "title": "Validation Failed",
 *   "status": 400,
 *   "detail": "One or more fields are invalid",
 *   "instance": "/api/v1/students",
 *   "code": "VALIDATION_FAILED",
 *   "timestamp": "2026-09-04T11:00:00Z",
 *   "errors": {
 *     "email": "Invalid email address",
 *     "name": "Name is mandatory"
 *   }
 * }
 * }</pre>
 *
 * @see ProblemDetail
 * @see ResponseEntityExceptionHandler
 * @see ErrorCode
 * @see ApplicationException
 */
@Slf4j
@RestControllerAdvice
public class GlobalExceptionHandler extends ResponseEntityExceptionHandler {

  /**
   * Constructs a standardized {@link ProblemDetail} containing standard RFC 9457 fields and custom
   * application extension properties ({@code code} and {@code timestamp}).
   *
   * @param errorCode the business or infrastructure {@link ErrorCode} defining the HTTP status and
   *     title
   * @param detail optional human-readable occurrence explanation; omitted from JSON if {@code null}
   *     or blank
   * @param request the active {@link HttpServletRequest} used to populate the {@code instance} URI
   * @return a populated {@link ProblemDetail} carrying core RFC 9457 fields and custom extensions
   * @see ErrorCode
   * @see ProblemDetail
   */
  private ProblemDetail buildProblem(
      ErrorCode errorCode, String detail, HttpServletRequest request) {

    ProblemDetail problem = ProblemDetail.forStatus(errorCode.getStatus());

    problem.setTitle(errorCode.getTitle());

    if (detail != null && !detail.isBlank()) {
      problem.setDetail(detail);
    }

    if (request != null) {
      problem.setInstance(URI.create(request.getRequestURI()));
    }

    problem.setProperty("code", errorCode.name());
    problem.setProperty("timestamp", Instant.now());

    return problem;
  }

  /**
   * Constructs a validation {@link ProblemDetail} enclosing structured field-level or
   * parameter-level errors.
   *
   * <p>Sets the error code to {@link ErrorCode#VALIDATION_FAILED}, provides a summary detail
   * message ({@code "One or more fields are invalid"}), and appends the provided error map as an
   * {@code errors} extension property in compliance with RFC 9457 guidelines for validation
   * representations.
   *
   * @param errors a map of invalid field or parameter names to their associated validation error
   *     messages
   * @param request the active {@link HttpServletRequest} used to populate the {@code instance} URI
   * @return a populated {@link ProblemDetail} containing validation metadata and the {@code errors}
   *     extension
   * @see #buildProblem(ErrorCode, String, HttpServletRequest)
   * @see ErrorCode#VALIDATION_FAILED
   */
  private ProblemDetail buildValidationProblem(
      Map<String, String> errors, HttpServletRequest request) {

    ProblemDetail problem =
        buildProblem(ErrorCode.VALIDATION_FAILED, "One or more fields are invalid", request);

    problem.setProperty("errors", errors);

    return problem;
  }

  /**
   * Intercepts and formats domain and application business exceptions derived from {@link
   * ApplicationException}.
   *
   * <p>Handles specific domain errors such as {@link ResourceNotFoundException} and {@link
   * DuplicateResourceException}. Retrieves the corresponding {@link ErrorCode} and optional
   * occurrence details to produce an appropriate {@link ProblemDetail} response.
   *
   * @param ex the application exception containing the machine-readable error code and optional
   *     detail
   * @param request the current {@link HttpServletRequest}
   * @return a {@link ResponseEntity} containing the generated {@link ProblemDetail} with the
   *     associated HTTP status
   * @see ApplicationException
   * @see ErrorCode
   */
  @ExceptionHandler(ApplicationException.class)
  public ResponseEntity<ProblemDetail> handleApplicationException(
      ApplicationException ex, HttpServletRequest request) {

    log.debug("Application exception [{}]", ex.getErrorCode().name());

    ProblemDetail problem = buildProblem(ex.getErrorCode(), ex.getDetail(), request);

    return ResponseEntity.status(ex.getErrorCode().getStatus()).body(problem);
  }

  /**
   * Intercepts and formats request body validation failures triggered by {@code @Valid} or
   * {@code @Validated} annotations on controller method arguments (e.g., DTOs).
   *
   * <p>Overrides {@link ResponseEntityExceptionHandler#handleMethodArgumentNotValid} to extract
   * field-level binding errors from {@link MethodArgumentNotValidException} into a clean key-value
   * map and attaches it as an {@code errors} extension property on the RFC 9457 {@link
   * ProblemDetail}.
   *
   * @param ex the validation exception capturing binding errors from {@link
   *     MethodArgumentNotValidException}
   * @param headers the HTTP headers to be written to the response
   * @param status the HTTP status code (HTTP 400 Bad Request)
   * @param request the current web request
   * @return a {@link ResponseEntity} enclosing an RFC 9457 validation {@link ProblemDetail}
   * @see MethodArgumentNotValidException
   * @see #buildValidationProblem(Map, HttpServletRequest)
   */
  @Override
  protected ResponseEntity<Object> handleMethodArgumentNotValid(
      MethodArgumentNotValidException ex,
      @NonNull HttpHeaders headers,
      @NonNull HttpStatusCode status,
      @NonNull WebRequest request) {

    Map<String, String> errors = new LinkedHashMap<>();

    ex.getBindingResult()
        .getFieldErrors()
        .forEach(error -> errors.put(error.getField(), error.getDefaultMessage()));

    HttpServletRequest servletRequest =
        (request instanceof ServletWebRequest swr) ? swr.getRequest() : null;

    log.debug("Validation failed with {} error(s)", errors.size());

    ProblemDetail problem = buildValidationProblem(errors, servletRequest);

    return createResponseEntity(problem, headers, status, request);
  }

  /**
   * Intercepts and formats method-parameter validation failures (e.g., constraints directly placed
   * on {@code @PathVariable}, {@code @RequestParam}, or {@code @RequestHeader}).
   *
   * <p>Overrides {@link ResponseEntityExceptionHandler#handleHandlerMethodValidationException}
   * introduced in modern Spring Framework versions. Extracts violations from {@link
   * HandlerMethodValidationException} parameter validation results into an {@code errors} extension
   * property.
   *
   * @param ex the validation exception capturing method parameter violations
   * @param headers the HTTP headers to be written to the response
   * @param status the HTTP status code (HTTP 400 Bad Request)
   * @param request the current web request
   * @return a {@link ResponseEntity} enclosing an RFC 9457 validation {@link ProblemDetail}
   * @see HandlerMethodValidationException
   * @see #buildValidationProblem(Map, HttpServletRequest)
   */
  @Override
  protected ResponseEntity<Object> handleHandlerMethodValidationException(
      @NonNull HandlerMethodValidationException ex,
      @NonNull HttpHeaders headers,
      @NonNull HttpStatusCode status,
      @NonNull WebRequest request) {

    Map<String, String> errors = new LinkedHashMap<>();

    ex.getParameterValidationResults()
        .forEach(
            result -> {
              String paramName = result.getMethodParameter().getParameterName();

              result
                  .getResolvableErrors()
                  .forEach(
                      resolvable ->
                          errors.put(
                              paramName != null ? paramName : "parameter",
                              resolvable.getDefaultMessage()));
            });

    HttpServletRequest servletRequest =
        (request instanceof ServletWebRequest swr) ? swr.getRequest() : null;

    log.debug("Handler method validation failed with {} error(s)", errors.size());

    ProblemDetail problem = buildValidationProblem(errors, servletRequest);

    return createResponseEntity(problem, headers, status, request);
  }

  /**
   * Intercepts and formats method argument type conversion failures before controller execution.
   *
   * <p>Typically triggered when a request contains a malformed path variable or query parameter
   * that cannot be converted to the required target type (for example, attempting to pass a
   * non-UUID string like {@code "999"} to an endpoint expecting a {@code UUID} path variable). Maps
   * to HTTP 400 Bad Request with {@link ErrorCode#INVALID_PARAMETER_TYPE}.
   *
   * @param ex the type mismatch exception capturing parameter name, input value, and expected
   *     target type
   * @param request the current {@link HttpServletRequest}
   * @return a {@link ResponseEntity} with HTTP 400 Bad Request enclosing an {@code
   *     INVALID_PARAMETER_TYPE} {@link ProblemDetail}
   * @see MethodArgumentTypeMismatchException
   * @see ErrorCode#INVALID_PARAMETER_TYPE
   */
  @ExceptionHandler(MethodArgumentTypeMismatchException.class)
  public ResponseEntity<ProblemDetail> handleMethodArgumentTypeMismatch(
      MethodArgumentTypeMismatchException ex, HttpServletRequest request) {

    String requiredType =
        ex.getRequiredType() != null ? ex.getRequiredType().getSimpleName() : "valid type";

    String detail =
        String.format(
            "Failed to convert parameter '%s' with value '%s' to required type '%s'",
            ex.getName(), ex.getValue(), requiredType);

    log.debug("Method argument type mismatch on parameter '{}'", ex.getName());

    ProblemDetail problem = buildProblem(ErrorCode.INVALID_PARAMETER_TYPE, detail, request);

    return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(problem);
  }

  /**
   * Intercepts database constraint violations (e.g., unique key constraint collisions or foreign
   * key violations) thrown by the persistence layer.
   *
   * <p>Maps the failure to HTTP 409 Conflict with {@link ErrorCode#DATA_INTEGRITY_VIOLATION} and
   * returns a sanitized client-facing message ({@code "The request conflicts with existing data."})
   * to prevent leakage of internal database table, column, or constraint names.
   *
   * @param ex the data integrity violation exception thrown by Spring Data JPA / Hibernate
   * @param request the current {@link HttpServletRequest}
   * @return a {@link ResponseEntity} with HTTP 409 Conflict enclosing a {@code
   *     DATA_INTEGRITY_VIOLATION} {@link ProblemDetail}
   * @see DataIntegrityViolationException
   * @see ErrorCode#DATA_INTEGRITY_VIOLATION
   */
  @ExceptionHandler(DataIntegrityViolationException.class)
  public ResponseEntity<ProblemDetail> handleDataIntegrityViolation(
      DataIntegrityViolationException ex, HttpServletRequest request) {

    log.warn("Database integrity violation occurred");

    ProblemDetail problem =
        buildProblem(
            ErrorCode.DATA_INTEGRITY_VIOLATION,
            "The request conflicts with existing data.",
            request);

    return ResponseEntity.status(HttpStatus.CONFLICT).body(problem);
  }

  /**
   * Fallback exception handler for unexpected checked or runtime exceptions.
   *
   * <p>Logs the full exception stack trace internally for diagnostic purposes while returning a
   * sanitized HTTP 500 Internal Server Error response to prevent exposing sensitive internal
   * infrastructure details.
   *
   * @param ex the uncaught exception
   * @param request the current {@link HttpServletRequest}
   * @return a {@link ResponseEntity} with HTTP 500 Internal Server Error enclosing an {@code
   *     INTERNAL_SERVER_ERROR} {@link ProblemDetail}
   * @see Exception
   * @see ErrorCode#INTERNAL_SERVER_ERROR
   */
  @ExceptionHandler(Exception.class)
  public ResponseEntity<ProblemDetail> handleUnexpectedException(
      Exception ex, HttpServletRequest request) {

    log.error("Unexpected error occurred while processing request", ex);

    ProblemDetail problem =
        buildProblem(ErrorCode.INTERNAL_SERVER_ERROR, "An unexpected error occurred", request);

    return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(problem);
  }
}
